@startuml SocketLib Class
namespace SocketLib{

interface IUdpSock{
    {abstract} Initialize(int port, int address, int family)
    {abstract} Finalize()
    {abstract} Bind()
    {abstract} Close()
    {abstract} Recieve()
    {abstract} Send()
}

interface ITcpSock{
    {abstract} Initialize(int port, int address, int family)
    {abstract} Finalize()
    {abstract} Accept()
    {abstract} Bind()
    {abstract} Close()
    {abstract} Listen()
    {abstract} Recieve()
    {abstract} Send()
}

class SocketInfo{
    -WSADATA m_wsa_data
    -SOCKET m_sock
    -sockaddr_in m_mine
    -sockaddr_in m_oppnent
}

class UdpSock{
    +Initialize()
    +Finalize()
    +Bind()
    +Close()
    +Recieve()
    +Send()    
}

class TcpSock{
    +Initialize()
    +Finalize()
    +Accept()
    +Bind()
    +Close()
    +Listen()
    +Recieve()
    +Send()
}

class SockError{

}

IUdpSock <|-- UdpSock
ITcpSock <|-- TcpSock
SocketInfo *-- UdpSock
SocketInfo *-- TcpSock
SockError <|-- runtime_error

}
@enduml
